### ISSUE TITLE
not able to run img2url 

### ISSUE THREAD

**Issue by cbweixin** [huntzhan/img2url#2]
steps to reproduce:
- install img2url by pip. 
```
  Found existing installation: PySocks 1.6.7
    Uninstalling PySocks-1.6.7:
      Successfully uninstalled PySocks-1.6.7
  Found existing installation: img2url 0.2.0
    Uninstalling img2url-0.2.0:
      Successfully uninstalled img2url-0.2.0
Successfully installed PyYAML-3.12 certifi-2017.11.5 chardet-3.0.4 docopt-0.6.2 future-0.16.0 idna-2.6 img2url-0.2.0 pyperclip-1.6.0 pysocks-1.6.7 qiniu-7.1.9 requests-2.18.4 urllib3-1.22
```
- run it
```
 Dropbox  Screenshots  $  img2url Screenshot\ 2017-08-27\ 16.00.31.png 
Traceback (most recent call last):
  File "/usr/local/bin/img2url", line 11, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python2.7/site-packages/img2url/main.py", line 99, in entry_point
    path, fields, RemoteConfig, RemoteOperation,
  File "/usr/local/lib/python2.7/site-packages/img2url/main.py", line 61, in upload_file
    exists_files = operator.list_remote()
  File "/usr/local/lib/python2.7/site-packages/img2url/remotes/github.py", line 254, in list_remote
    return list_repo(self.config.fields)
  File "/usr/local/lib/python2.7/site-packages/img2url/remotes/github.py", line 232, in list_repo
    assert_status_code(rep, 200)
  File "/usr/local/lib/python2.7/site-packages/img2url/remotes/github.py", line 118, in assert_status_code
    raise RuntimeError('FATAL on making request')
RuntimeError: FATAL on making request
```

**Comment by cbweixin** [comment]
please close it, it is false alarm. I put the wrong token which cause this issue.
